### ISSUE TITLE
Upgrade to latest Payload Version

### ISSUE THREAD

**Issue by vdiaz1130** [binarystarter/binarystarter-angular#4]
Nice starter. I tried to get it to work with the latest version of Payload but was not able.

**Comment by florinmtsc** [comment]
Hi, thank you!

I will upgrade until end of next week to angular 17 and the latest version of payload.

**Comment by florinmtsc** [comment]
Hi, I have updated to the latest versions.

I apologize for being so late, I actually was done when I mentioned but I had a problem compiling the payload config when running the production build. Everything works now!
